apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: workload-vsphere-tkg1
  namespace: demo1
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vsan-default-storage-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 15Gi
        - name: kubelet
          mountPath: /var/lib/kubelet
          capacity:
            storage: 15Gi
      tkr:
        reference:
          name: v1.21.6---vmware.1-tkg.1.b3d708a
    nodePools:
    - name: node-pool-1
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vsan-default-storage-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 30Gi
        - name: kubelet
          mountPath: /var/lib/kubelet
          capacity:
            storage: 30Gi
      tkr:
        reference:
          name: v1.21.6---vmware.1-tkg.1.b3d708a
  settings:
    storage:
      classes: ["vsan-default-storage-policy"]
      defaultClass: vsan-default-storage-policy
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["10.244.0.0/16"]
      services:
        cidrBlocks: ["192.168.1.0/24"]
