apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: workload-vsphere-tkg3
  namespace: demo1
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.0.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.23.8---vmware.2-tkg.2-zshippable
    controlPlane:
#      metadata:
#        annotations:
#          run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
      replicas: 3
    workers:
      machineDeployments:
        - class: node-pool
          failureDomain: zone1
          name: node-pool-1
          replicas: 1
#          metadata:
#            annotations:
#              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
         - class: node-pool
          failureDomain: zone2
          name: node-pool-2
          replicas: 1
#          metadata:
#            annotations:
#              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu          
        - class: node-pool
          failureDomain: zone3
          name: node-pool-3
          replicas: 1
#          metadata:
#            annotations:
#              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    variables:
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: tanzu
      - name: defaultStorageClass
        value: tanzu
      - name: clusterEncryptionConfigYaml
        value: |
          apiVersion: apiserver.config.k8s.io/v1
          kind: EncryptionConfiguration
          resources:
            - resources:
                - secrets
              providers:
                - aescbc:
                    keys:
                      - name: key1
                        secret: QiMgJGYXudtljldVyl+AnXQQlk7r9iUXBfVKqdEfKm8=
                - identity: {}
# ADDITIONAL VALUES
      - name: nodePoolVolumes
        value:
        - capacity:
            storage: "30Gi"
          mountPath: "/var/lib/containerd"
          name: containerd
          storageClass: tanzu
      - name: controlPlaneVolumes
        value:
        - capacity:
            storage: "4Gi"
          mountPath: "/var/lib/etcd"
          name: etcd
          storageClass: tanzu
