apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: workload-vsphere-tkg1
  namespace: demo1
spec:
  distribution:
    version: v1.21.6
  topology:
    controlPlane:
      count: 1
      class: best-effort-medium
      storageClass: vsan-default-storage-policy
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 4Gi
    workers:
      count: 2
      class: best-effort-medium
      storageClass: vsan-default-storage-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 30Gi
  settings:
    network:
#      serviceDomain: "k8s.lab.test"
      services:
        cidrBlocks: ["198.51.100.0/24"]
      pods:
        cidrBlocks: ["192.0.0.0/16"]
    storage:
      classes: ["vsan-default-storage-policy"]
      defaultClass: vsan-default-storage-policy
