# tanzu management-cluster create ubuntu-nv-1 --file management-cluster-config.yaml -v 6
AVI_CA_DATA_B64: {{ BASE64 }}
AVI_CLOUD_NAME: tkg-cloud
AVI_CONTROL_PLANE_HA_PROVIDER: "true"
AVI_CONTROL_PLANE_NETWORK: Workload0-VDS-PG
AVI_CONTROL_PLANE_NETWORK_CIDR: 192.168.102.0/23
AVI_CONTROLLER: 192.168.100.58
AVI_DATA_NETWORK: Workload0-VDS-PG
AVI_DATA_NETWORK_CIDR: 192.168.102.0/23
AVI_ENABLE: "true"
AVI_LABELS: ""
AVI_MANAGEMENT_CLUSTER_CONTROL_PLANE_VIP_NETWORK_CIDR: 192.168.102.0/23
AVI_MANAGEMENT_CLUSTER_CONTROL_PLANE_VIP_NETWORK_NAME: Workload0-VDS-PG
AVI_MANAGEMENT_CLUSTER_SERVICE_ENGINE_GROUP: Default-Group
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR: 192.168.102.0/23
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME: Workload0-VDS-PG
AVI_PASSWORD: <encoded:Vk13YXJlMSE=>
AVI_SERVICE_ENGINE_GROUP: Default-Group
AVI_USERNAME: admin
CLUSTER_ANNOTATIONS: 'description:,location:'
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: ubuntu-nv-1
CLUSTER_PLAN: dev
ENABLE_AUDIT_LOGGING: "true"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: oidc
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: {{ CLIENT-ID }}
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: <encoded:{{SECRET}}>
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: groups
OIDC_IDENTITY_PROVIDER_ISSUER_URL: https://dev-5841773.okta.com
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: openid,groups,email
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: email
OS_ARCH: amd64
OS_NAME: ubuntu
OS_VERSION: "20.04"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
VSPHERE_CONTROL_PLANE_DISK_GIB: "20"
VSPHERE_CONTROL_PLANE_ENDPOINT: ""
VSPHERE_CONTROL_PLANE_MEM_MIB: "4096"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /Pacific-Datacenter
VSPHERE_DATASTORE: /Pacific-Datacenter/datastore/vsanDatastore
VSPHERE_FOLDER: /Pacific-Datacenter/vm
VSPHERE_INSECURE: "false"
VSPHERE_NETWORK: /Pacific-Datacenter/network/Workload0-VDS-PG
VSPHERE_PASSWORD: <encoded:Vk13YXJlMSE=>
VSPHERE_RESOURCE_POOL: /Pacific-Datacenter/host/Supervisor-Cluster/Resources
VSPHERE_SERVER: 192.168.100.50
VSPHERE_SSH_AUTHORIZED_KEY: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDD8VIQfTGIF6PVIgMG/qAUmRoBXCrj3HOc+8pGtKueSiJSrTqlx/p5ydWGxDrPg3PzmR0EioflR5ZpsY3w4/KZmPgQVIFhnurBw0b1wZpF++5LLuohp7A8H94MD9elPtRamnUr6SY4GQXUoXOpfSpoQeCb0u8BE12yfyS7+xxzXEyY2hsP4wsI9hCeHn9lnEFA1SVKl7VlzHXJNSgmIZ8UAqSjhln2cU1lt2QfD2EYNBXf5By83UDB4lCFyvXA1NQjE+RlEhMxUyThkfZ1khHj+3cFysLoV92hUmTMlQg3/n9rz/3OL2xUaE1yRm7BvR77FpMcLtVqHsiLl6oIKz8Bd/JG7jTnmQuhoW2OdyWHHqQIMu/TDwJQaBiIUOt4xsOEg9hXUegNqoIqqUGjiN5e4fB5JXjuItVHp2zZplhSR37qP36b/QS1Z1EuXW2U9M0iCKjrBlKxrR+Zh4K6ghQaq0J3f8YH8WulGk/qhwL66As5IqrgEgfKOu16kHpIcyM4NTRVYABuAl8YENQVrP7e0fmUY/7LltNJ6VDqps19rJhZKdyJuAXgReBk+9qeU9o5tVFP3oUNUODRCkDWvAmdKSCCAEl0F5R01Kdm10eoafoRR3v1ewoU79Y1J1yQB6pBuHT1BfjVps/wo02O33QizU10ISnwRL/LYhz22CNj2w== navneetv@vmware.com
VSPHERE_TLS_THUMBPRINT: F6:E4:8B:45:7C:43:7A:2E:A5:BC:2E:F2:0B:7C:88:1B:21:34:7B:F4
VSPHERE_USERNAME: administrator@vsphere.local
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "8192"
VSPHERE_WORKER_NUM_CPUS: "2"
WORKER_ROLLOUT_STRATEGY: ""
